---
title: "Quizzes and Exams"
---

Review materials and solutions to quizzes and exams will be posted here.

+------+----------------------------------------------------------+---------------------------------------------------------------+
| Type | Description/Review Materials                             | Solutions                                                     |
+======+==========================================================+===============================================================+
| Quiz | Chapter 1: [pdf](exams/ch1/stat242_quizzes.pdf)          | Solutions: [pdf](exams/ch1/stat242_quiz_solutions.pdf)        |
|      |                                                          |                                                               |
|      | The are several other topics from Chapter 1 that are also|                                                               |
|      | important, but that didn't make it onto quizzes. Please  |                                                               |
|      | also read the book and review in-class materials.        |                                                               |
+------+----------------------------------------------------------+---------------------------------------------------------------+
| Quiz | Chapter 2: [pdf](exams/ch2/stat242_quizzes.pdf)          | Solutions: [pdf](exams/ch2/stat242_quiz_solutions.pdf)        |
+------+----------------------------------------------------------+---------------------------------------------------------------+
| Quiz | Sections 5.2 and 6.2 (t tests):                          | Solutions: [pdf](exams/Ch52_62/stat242_quiz_solutions.pdf)    |
|      | [pdf](exams/Ch52_62/stat242_quizzes.pdf)                 |                                                               |
+------+----------------------------------------------------------+---------------------------------------------------------------+
| Quiz | Sections 5.3 and 5.4 (F tests):                          | Solutions: [pdf](exams/ch53_54/stat242_quiz_solutions.pdf)    |
|      | [pdf](exams/ch53_54/stat242_quizzes.pdf)                 |                                                               |
+------+----------------------------------------------------------+---------------------------------------------------------------+
| Quiz | Sections 6.3 and 6.4 (multiple comparisons):             | Solutions: [pdf](exams/ch63_64/stat242_quiz_solutions.pdf)    |
|      | [pdf](exams/ch63_64/stat242_quizzes.pdf)                 |                                                               |
+------+----------------------------------------------------------+---------------------------------------------------------------+
| Quiz | Section 5.5 and Chapter 3 (ANOVA conditions):            | Solutions: [pdf](exams/ch55_3a/stat242_quiz_solutions.pdf)    |
|      | [pdf](exams/ch55_3a/stat242_quizzes.pdf)                 |                                                               |
+------+----------------------------------------------------------+---------------------------------------------------------------+
| Quiz | Section 5.5 and Chapter 3 (ANOVA transformations):       | Solutions: [pdf](exams/ch55_3b/stat242_quiz_solutions.pdf)    |
|      | [pdf](exams/ch55_3b/stat242_quizzes.pdf)                 |                                                               |
+------+----------------------------------------------------------+---------------------------------------------------------------+
| Quiz | Chapter 7 (Simple linear regression):                    | Solutions: [pdf](exams/ch7/stat242_quiz_solutions.pdf)        |
|      | [pdf](exams/ch7/stat242_quizzes.pdf)                     |                                                               |
+------+----------------------------------------------------------+---------------------------------------------------------------+
| Quiz | Chapter 8 (Simple linear regression conditions):         | Solutions: [pdf](exams/ch8/stat242_quiz_solutions.pdf)        |
|      | [pdf](exams/ch8/stat242_quizzes.pdf)                     |                                                               |
+------+----------------------------------------------------------+---------------------------------------------------------------+
| Quiz | Chapters 9 and 10 (Multiple Lines):                      |Solutions: [pdf](exams/ch9_10_lines/stat242_quiz_solutions.pdf)|
|      | [pdf](exams/ch9_10_lines/stat242_quizzes.pdf)            |                                                               |
+------+----------------------------------------------------------+---------------------------------------------------------------+
| Quiz | Chapter 13 (Two-way ANOVA):                              | Solutions: [pdf](exams/ch13/stat242_quiz_solutions.pdf)       |
|      | [pdf](exams/ch13/stat242_quizzes.pdf)                    |                                                               |
+------+----------------------------------------------------------+---------------------------------------------------------------+
