---
title: "Homework"
---

Here's a guide to getting homework assignments that are on GitHub into RStudio: [pdf](resources/Stat242-github-setup.pdf)

Here's a guide to getting homework assignments from RStudio into Gradescope: [pdf](homework/hw_submission/Stat242-hw-submission.pdf)

I realize that this is kindof a pain!  Let me know if you run into any problems with this.

+------------------+--------------------------------------------------------------------------------------+-------------------+----------+--------------------------------------------------------------------------+
| Assignment       | Description                                                                          | Due Date          | Value    | Solutions                                                                |
+==================+======================================================================================+===================+==========+==========================================================================+
| HW0              | Optional Data Camp assignments.                                                      |    N/A            | 0        |  N/A                                                                     |
|                  |                                                                                      |                   |(optional)|                                                                          |
|                  | Register for our course on Data Camp at this link, and complete the assignment there:|                   |          |                                                                          |
|                  | https://www.datacamp.com/groups/shared_links/e05929250408228fa302681f53f66bdc48e8142d|                   |          |                                                                          |
|                  |                                                                                      |                   |          |                                                                          |
|                  | If you are already comfortable with R, you don't need to do this.  If you would like |                   |          |                                                                          |
|                  | a review, you are welcome to do this.  **If you haven't seen R before, you should**  |                   |          |                                                                          |
|                  | **treat this as a required assignment even though it won't be graded.**  If you have |                   |          |                                                                          |
|                  | not used R much/at all yet, this assignment may feel overwhelming.  Don't worry, we  |                   |          |                                                                          |
|                  | will talk about this material in more depth in future classes.  This is a first pass.|                   |          |                                                                          |
+------------------+--------------------------------------------------------------------------------------+-------------------+----------+--------------------------------------------------------------------------+
| HW1              | Chapter 1.  Use the instructions above to clone the assignment into RStudio, using   | Sept. 13          | 1        | https://github.com/mhc-stat242-f2019/HW1-solutions/blob/master/HW1.pdf   |
|                  | this link for the repository URL in step 6:                                          |                   |          |                                                                          |
|                  | https://github.com/mhc-stat242-f2019/HW1.git                                         |                   |          |                                                                          |
+------------------+--------------------------------------------------------------------------------------+-------------------+----------+--------------------------------------------------------------------------+
| HW2              | Chapter 2.  Use the instructions above to clone the assignment into RStudio, using   | Sept. 20          | 1        | https://github.com/mhc-stat242-f2019/HW2-solutions/blob/master/HW2.pdf   |
|                  | this link for the repository URL in step 6:                                          |                   |          |                                                                          |
|                  | https://github.com/mhc-stat242-f2019/HW2.git                                         |                   |          |                                                                          |
+------------------+--------------------------------------------------------------------------------------+-------------------+----------+--------------------------------------------------------------------------+
| HW3              | Sections 5.2 and 6.2.  Use the instructions above to clone the assignment into       | Sept. 27          | 1        | https://github.com/mhc-stat242-f2019/HW3-solutions/blob/master/HW3.pdf   |
|                  | RStudio, using this link for the repository URL in step 6:                           |                   |          |                                                                          |
|                  | https://github.com/mhc-stat242-f2019/HW3.git                                         |                   |          |                                                                          |
+------------------+--------------------------------------------------------------------------------------+-------------------+----------+--------------------------------------------------------------------------+
| HW4              | Sections 5.3, 5.4, 6.3, and 6.4.  Use the instructions above to clone the assignment | Oct. 4            | 1        | https://github.com/mhc-stat242-f2019/HW4-solutions/blob/master/HW4.pdf   |
|                  | into RStudio, using this link for the repository URL in step 6:                      |                   |          |                                                                          |
|                  | https://github.com/mhc-stat242-f2019/HW4.git                                         |                   |          |                                                                          |
+------------------+--------------------------------------------------------------------------------------+-------------------+----------+--------------------------------------------------------------------------+
| HW5              | Sections 3, 5.5, 6.3, and 6.4.    Use the instructions above to clone the assignment | Oct. 18           | 1        | https://github.com/mhc-stat242-f2019/HW5-solutions/blob/master/HW5.pdf   |
|                  | into RStudio, using this link for the repository URL in step 6:                      |                   |          |                                                                          |
|                  | https://github.com/mhc-stat242-f2019/HW5.git                                         |                   |          |                                                                          |
+------------------+--------------------------------------------------------------------------------------+-------------------+----------+--------------------------------------------------------------------------+
| HW6              | Chapter 7.    Use the instructions above to clone the assignment                     | Oct. 25           | 1        | https://github.com/mhc-stat242-f2019/HW6-solutions/blob/master/HW6.pdf   |
|                  | into RStudio, using this link for the repository URL in step 6:                      |                   |          |                                                                          |
|                  | https://github.com/mhc-stat242-f2019/HW6.git                                         |                   |          |                                                                          |
+------------------+--------------------------------------------------------------------------------------+-------------------+----------+--------------------------------------------------------------------------+
| HW7              | Chapter 8.    Use the instructions above to clone the assignment                     | Nov. 1            | 1        | https://github.com/mhc-stat242-f2019/HW7-solutions/blob/master/HW7.pdf   |
|                  | into RStudio, using this link for the repository URL in step 6:                      |                   |          |                                                                          |
|                  | https://github.com/mhc-stat242-f2019/HW7.git                                         |                   |          |                                                                          |
+------------------+--------------------------------------------------------------------------------------+-------------------+----------+--------------------------------------------------------------------------+
| HW8              | Chapters 9 and 10.    Use the instructions above to clone the assignment             | Nov. 8            | 1        | https://github.com/mhc-stat242-f2019/HW8-solutions/blob/master/HW8.pdf   |
|                  | into RStudio, using this link for the repository URL in step 6:                      |                   |          |                                                                          |
|                  | https://github.com/mhc-stat242-f2019/HW8.git                                         |                   |          |                                                                          |
+------------------+--------------------------------------------------------------------------------------+-------------------+----------+--------------------------------------------------------------------------+
| HW9              | Chapter 13.    Use the instructions above to clone the assignment                    | Nov. 15           | 1        | https://github.com/mhc-stat242-f2019/HW9-solutions/blob/master/HW9.pdf   |
|                  | into RStudio, using this link for the repository URL in step 6:                      |                   |          |                                                                          |
|                  | https://github.com/mhc-stat242-f2019/HW9.git                                         |                   |          |                                                                          |
+------------------+--------------------------------------------------------------------------------------+-------------------+----------+--------------------------------------------------------------------------+
| HW10             | Chapters 11-12.  Use the instructions above to clone the assignment                  | Nov. 26           | 1        | https://github.com/mhc-stat242-f2019/HW10-solutions/blob/master/HW10.pdf |
|                  | into RStudio, using this link for the repository URL in step 6:                      |                   |          |                                                                          |
|                  | https://github.com/mhc-stat242-f2019/HW10.git                                        |                   |          |                                                                          |
+------------------+--------------------------------------------------------------------------------------+-------------------+----------+--------------------------------------------------------------------------+
