---
title: "Intermediate Statistics"
---

**Instructor:** Evan Ray

**Email:** eray@mtholyoke.edu

**Office:** Clapp 404C

**Office Hours:** I have regularly scheduled office hours at the times below.  These are times I guarantee I will be in my office and available, but I am also available by appointment at other times; send an email to set up a time to meet.

 * Monday 4pm-5pm
 * Tuesday 1pm-2pm
 * Thursday 11am-12pm
 * Friday 2pm-3pm

**Extra Help:** We have a TA for this class.  Yian Ding will be available to answer questions on Thursday evenings from 7-9 pm in Clapp 127.  You should also think of this as a time and space to meet up with other students to work together on homework assignments.

**Piazza:** We are registered on Piazza at [https://piazza.com/mtholyoke/fall2019/stat242](https://piazza.com/mtholyoke/fall2019/stat242).  You can ask and answer questions there, anonymously if you want, and everyone in the class will be able to see and contribute to the answers.

**Syllabus:** [pdf](syllabus/syllabus_stat_242.pdf)

Please use the navigation menu above to go to the schedule, homework assignments, and materials related to quizzes and exams.
