\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=0.6in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\providecommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{}
    \pretitle{\vspace{\droptitle}}
  \posttitle{}
    \author{}
    \preauthor{}\postauthor{}
    \date{}
    \predate{}\postdate{}
  
\usepackage{booktabs}

\begin{document}

\hypertarget{stat-242-quiz-topics-drawn-from-sections-5.5-and-chapter-3}{%
\subsection{Stat 242 Quiz -- Topics Drawn from Sections 5.5 and Chapter
3}\label{stat-242-quiz-topics-drawn-from-sections-5.5-and-chapter-3}}

\hypertarget{whats-your-name-____________________}{%
\subsection{What's Your Name?
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_}\label{whats-your-name-____________________}}

Researchers examined the time in minutes before an insulating fluid lost
its insulating property when the fluid was exposed to each of two
different voltages. They had eight samples of the fluid, 3 of which were
randomly assigned to receive 26 kV of electricity and 5 of which were
randomly assigned to receive 28 kV of electricity. The times until loss
of insulating properties were skewed right with several outliers, so
they performed a logarithmic transformation; after transformation the
standard deviations within each group were similar.

The R code and output below shows the results of their analysis:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{insulation }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(voltage) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarize}\NormalTok{(}
    \KeywordTok{mean}\NormalTok{(log_time)}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 2 x 2
##   voltage `mean(log_time)`
##   <fct>              <dbl>
## 1 v26                 5.62
## 2 v28                 5.33
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lm_fit <-}\StringTok{ }\KeywordTok{lm}\NormalTok{(log_time }\OperatorTok{~}\StringTok{ }\NormalTok{voltage, }\DataTypeTok{data =}\NormalTok{ insulation)}
\KeywordTok{summary}\NormalTok{(lm_fit)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = log_time ~ voltage, data = insulation)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.8678 -0.7580  0.0495  1.6680  2.1270 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)   
## (Intercept)   5.6239     1.2418   4.529  0.00398 **
## voltagev28   -0.2945     1.5707  -0.188  0.85744   
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 2.151 on 6 degrees of freedom
## Multiple R-squared:  0.005826,   Adjusted R-squared:  -0.1599 
## F-statistic: 0.03516 on 1 and 6 DF,  p-value: 0.8574
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{confint}\NormalTok{(lm_fit)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                 2.5 %   97.5 %
## (Intercept)  2.585411 8.662404
## voltagev28  -4.137955 3.548901
\end{verbatim}

\newpage

\hypertarget{interpret-the-estimated-mean-log-times-until-loss-of-insulating-properties-calculated-above-in-terms-of-what-they-say-about-a-measure-of-the-center-of-the-distribution-of-times-on-the-original-data-scale-in-minutes.}{%
\paragraph{1. Interpret the estimated mean log times until loss of
insulating properties calculated above in terms of what they say about a
measure of the center of the distribution of times on the original data
scale (in
minutes).}\label{interpret-the-estimated-mean-log-times-until-loss-of-insulating-properties-calculated-above-in-terms-of-what-they-say-about-a-measure-of-the-center-of-the-distribution-of-times-on-the-original-data-scale-in-minutes.}}

You may use the following R output:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{exp}\NormalTok{(}\FloatTok{5.62}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 275.8894
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{exp}\NormalTok{(}\FloatTok{5.33}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 206.438
\end{verbatim}

We estimate that the median time before loss of insulating property in
the ``population'' of samples of this fluid when exposed to 26 kV of
electricity is 275.9 minutes. We estimate that the population median
when exposed to 28 kV of electricity is 206.4 minutes.

\vspace{6cm}

\hypertarget{the-researchers-calculated-an-estimate-and-a-95-confidence-interval-for-the-difference-in-mean-log-times.-interpret-what-the-confidence-interval-says-about-the-relationship-between-a-measure-of-the-center-of-the-distribution-of-times-for-each-group-on-the-original-data-scale-in-minutes.-in-your-answer-include-a-description-of-the-meaning-of-the-phrase-95-confident.}{%
\paragraph{2. The researchers calculated an estimate and a 95\%
confidence interval for the difference in mean log times. Interpret what
the confidence interval says about the relationship between a measure of
the center of the distribution of times for each group on the original
data scale (in minutes). In your answer, include a description of the
meaning of the phrase ``95\%
confident''.}\label{the-researchers-calculated-an-estimate-and-a-95-confidence-interval-for-the-difference-in-mean-log-times.-interpret-what-the-confidence-interval-says-about-the-relationship-between-a-measure-of-the-center-of-the-distribution-of-times-for-each-group-on-the-original-data-scale-in-minutes.-in-your-answer-include-a-description-of-the-meaning-of-the-phrase-95-confident.}}

You may use the following R output:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{exp}\NormalTok{(}\OperatorTok{-}\FloatTok{4.14}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.01592285
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{exp}\NormalTok{(}\FloatTok{3.55}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 34.81332
\end{verbatim}

We are 95\% confident that the median time until loss of insulating
properties in the ``population'' when exposed to 28 kV of electricity is
between 0.016 and 34.813 times the median when exposed to 26 kV of
electricity

For 95\% of samples, a confidence interval calculated using this
procedure would include the ratio of the medians for these groups.


\end{document}
