---
title: "Mathematics in R Markdown"
author: "Evan Ray, adapted from R Pruim"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<style type="text/css">
td
{
    padding:5px 10px 5px 10px;
}
</style>

## Math inside RMarkdown

You may want to include math like greek symbols, etc., in your R Markdown documents.  In this class, this is totally optional.  If you want a $\mu$ in your document, you can just type "mu" instead and forget about the extra complication.  However, this document describes how to put math into your write up in case you want to.  It will definitely look nicer that way :)

In a text chunk, you can use mathematical notation if you surround it by 
dollar signs `$` for inline mathematics  and `$$` for displayed equations.
**Do not leave a space between the `$` and your mathematical notation**.
The mathematical typesetting is based on LaTeX, so if you need to search 
for the way to make a particular symbol, include `latex` in your search.

In LaTeX, curly braces (`{` and `}`) are used to surround items that are 
 to be considered as one object from LaTeX's perspective.  
 Without them, usually the next letter or digit will be used, 
 but that isn't usually what you want.  For example 
 `$\mu^null$` produces $\mu^null$, but 
 `$\mu^{null}$` produces $\mu^{null}$.

## Mathematical Notation

Here are some common mathematical things you might use in statistics


<table>
<tr><td>$x = y$</td><td> `$x = y $` </td> </tr>
<tr><td>$x < y$</td><td> `$x < y $` </td> </tr>
<tr><td>$x > y$</td><td> `$x > y $` </td> </tr>
<tr><td>$x \le y$</td><td> `$x \leq y $` </td> </tr>
<tr><td>$x \ge y$</td><td> `$x \geq y $` </td> </tr>
<tr><td>$x \neq y$</td><td> `$x \neq y $` </td> </tr>
<tr><td>$x^{n}$</td><td> `$x^{n}$` </td> </tr>
<tr><td>$x_{n}$</td><td> `$x_{n}$` </td> </tr>
<tr><td>$\bar{x}$</td><td> `$\bar{x}$` </td> </tr>
<tr><td>$\hat{x}$</td><td> `$\hat{x}$` </td> </tr>
<tr><td>$\frac{a}{b}$ </td><td> `$\frac{a}{b}$`</td> </tr>
<tr><td>$X \sim \text{Normal}(\mu, \sigma)$</td><td> `$X \sim \text{Normal}(\mu, \sigma)$`</td> </tr>
</table>

## Greek Letters

<table>
<tr><td>$\alpha A$</td><td>`$\alpha A$`</td><td>$\nu N$</td><td>`$\nu N$`</td></tr>
<tr><td>$\beta B$</td><td>`$\beta B$`</td><td>$\xi\Xi$</td><td>`$\xi\Xi$`</td></tr>
<tr><td>$\gamma \Gamma$</td><td>`$\gamma \Gamma$`</td><td>$o O$</td><td>`$o O$` (omicron)</td></tr>
<tr><td>$\delta \Delta$</td><td>`$\delta \Delta$`</td><td>$\pi \Pi$</td><td>`$\pi \Pi$`</td></tr>
<tr><td>$\epsilon \varepsilon E$</td><td>`$\epsilon \varepsilon E$`</td><td>$\rho\varrho P$</td><td>`$\rho\varrho P$`</td></tr>
<tr><td>$\zeta Z$</td><td>`$\zeta Z	\sigma \,\!$`</td><td>$\sigma \Sigma$</td><td>`$\sigma \Sigma$`</td></tr>
<tr><td>$\eta H$</td><td>`$\eta H$`</td><td>$\tau T$</td><td>`$\tau T$`</td></tr>
<tr><td>$\theta \vartheta \Theta$</td><td>`$\theta \vartheta \Theta$`</td> <td>$\upsilon \Upsilon$</td><td>`$\upsilon \Upsilon$`</td></tr>
<tr><td>$\iota I$</td><td>`$\iota I$`</td><td>$\phi \varphi \Phi$</td><td>`$\phi \varphi \Phi$`</td></tr>
<tr><td>$\kappa K$</td><td>`$\kappa K$`</td><td>$\chi X$</td><td>`$\chi X$`</td></tr>
<tr><td>$\lambda \Lambda$</td><td>`$\lambda \Lambda$`</td><td>$\psi \Psi$</td><td>`$\psi \Psi$`</td></tr>
<tr><td>$\mu M$</td><td>`$\mu M$`</td><td>$\omega \Omega$</td><td>`$\omega \Omega$`</td></tr>
</table>

## Source

This document is adapted from Randall Pruim's version here: https://www.calvin.edu/~rpruim/courses/s341/S17/from-class/MathinRmd.html

